spring:
    datasource:
#        url: jdbc:postgresql://192.168.6.97:5432/garnet2
#        url: jdbc:postgresql://localhost:5432/test_db
#        username: test
#        password: 123456

        url: jdbc:postgresql://192.168.108.100/garnet_test
        username: garnet
        password: garnet
        driverClassName: org.postgresql.Driver

#        url: jdbc:oracle:thin:@192.168.0.10:1521:whxy
#        username: ming
#        password: 123456
#        driverClassName: oracle.jdbc.OracleDriver