spring:
    datasource:
        url: jdbc:oracle:thin:@192.168.0.10:1521:whxy
        username: ming
        password: 123456
        driverClassName: oracle.jdbc.OracleDriver
#        platform: oracle
#        type: com.alibaba.druid.pool.DruidDataSource
#        # 下面为连接池的补充设置，应用到上面所有数据源中
#        # 初始化大小，最小，最大
#        initialSize: 1
#        minIdle: 3
#        maxActive: 20
#        # 配置获取连接等待超时的时间
#        maxWait: 60000
#        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#        timeBetweenEvictionRunsMillis: 60000
#        # 配置一个连接在池中最小生存的时间，单位是毫秒
#        minEvictableIdleTimeMillis: 30000
##        validationQuery: select 'x'
#        testWhileIdle: true
#        testOnBorrow: false
#        testOnReturn: false

#        connectionProperties: druid.stat.mergeSql=true