###############################Web配置######################################
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 12306
    context-path: /garnet

spring:
    profiles:
        active: dev
#        active: local
    # AOP config
    aop:
      auto: true
      proxy-target-class: false
    devtools:
        restart:
          additional-exclude: views/**
# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/*.xml
    configLocation: classpath:mybatis.xml