spring:
    datasource:
#        url: jdbc:postgresql://192.168.6.97:5432/garnet2
        url: jdbc:postgresql://localhost:5432/garnet
        username: postgres
        password: 123456
        driverClassName: org.postgresql.Driver