###############################Web配置######################################
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 12306
    context-path: /garnet

spring:
    profiles:
        active: local
#        active: dev
#        active: oracle
    # AOP config
    aop:
      auto: true
      proxy-target-class: false
    devtools:
        restart:
          additional-exclude: views/**
# Mybatis配置
#mybatis:
#    mapperLocations: classpath:mapper/*.xml
#    configLocation: classpath:mybatis.xml

mybatis:
#    mapper-locations: classpath:mapperOracle/*.xml
    mapper-locations: classpath:mapperPostgres/*.xml
    type-aliases-packag: com.richstonedt.garnet.model

