spring:
    datasource:
#        url: jdbc:postgresql://192.168.111.100:5432/garnet
        url: jdbc:postgresql://192.168.108.100:5432/garnet
        username: garnet
        password: garnet
        driverClassName: org.postgresql.Driver